"""empty message

Revision ID: 32339401930c
Revises: afdf0b235d0f
Create Date: 2024-07-14 15:50:59.098726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32339401930c'
down_revision: Union[str, None] = 'afdf0b235d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('some_field', postgresql.ENUM('pending', 'completed', 'cancelled', name='orderstatus', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'some_field')
    # ### end Alembic commands ###
