"""empty message

Revision ID: fcd79637a1c5
Revises: 64689b14b8c7
Create Date: 2024-07-13 22:32:03.752827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd79637a1c5'
down_revision: Union[str, None] = '64689b14b8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_item_user_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'items', ['item_id'], ['id'])
    op.drop_column('order_item', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_user_id_fkey', 'order_item', 'users', ['user_id'], ['id'])
    op.drop_column('order_item', 'item_id')
    # ### end Alembic commands ###
